# Site settings
title: Jingyu Yang, A programmer 
tag_text: Self Introduction 
description: This is a blog of jingleyang. All contents are about programming, Linux and security. 
# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
